name: Pipeline in pull request
on:
    pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Run eslint
        run: npm run lint
      - name: Run tests
        run: npm run test
        env:
          BOTCITY_SERVER: ${{ secrets.BOTCITY_SERVER }}
          BOTCITY_LOGIN: ${{ secrets.BOTCITY_LOGIN }}
          BOTCITY_KEY: ${{ secrets.BOTCITY_KEY }}
      - name: Execute build 🔧
        run: npm run build